### ISSUE TITLE
new package template issue

### ISSUE THREAD

**Issue by adrienc921** [opensemanticsearch/open-semantic-search#46] opened 2017-07-10 13:32 UTC
Hello,

I've installed the new packaged and it fixes the python3 dependency but I think some elements are not linked. I've got an error message saying that Django/Python can't find the templates for each of the apps. - search-list / thesaurus / datasources.

I've tried specifying the template path directly to test but it doesn't work.

Any idea?

Thanks

Here is the error output:

Request Method:
--
http://xxx/search-apps/search-list/
1.10.7
TemplateDoesNotExist
index.html
/usr/lib/python3/dist-packages/django/template/loader.py in get_template, line 25
/usr/bin/python3
3.5.3
['/var/lib/opensemanticsearch',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/usr/local/lib/python3.5/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3/dist-packages/opensemanticetl',
 '/']
Mon, 10 Jul 2017 13:26:16 +0000

**Comment by opensemanticsearch** [comment] 2017-07-13 20:03
I can't reproduce this with new version by some first tests.

Which Linux distribution (Debian/Ubuntu) and version do you use?

How did you the installation? Command line dpkg or Software installation UI of Ubuntu?

**Comment by Mandalka** [comment] 2017-08-29 15:44
The different Django apps are using templates from other apps for integrated menus, too. Installed all open semantic search apps with its general config (Django app opensemanticsearch) or removed links to the ones not installed?

If not this problem and not solved by the last releases please reopen.

**Comment by opensemanticsearch** [comment] 2017-10-07 16:43
Can reproduce it on Debian Stretch Django version.
Solution (will be part of next weeks release): Define/config new form of template settings in Django project config.

**Comment by Mandalka** [comment] 2017-10-09 09:43
The template settings are now upgraded to newest Django version.

**Closed by Mandalka** 2017-10-09 09:43 UTC
